version: "3.9"
services:
  redis:
    container_name: "nos-redis"
    image: "redis:latest"
    ports:
      - "6969:6969"
  mongo:
    container_name: "nos-db"
    image: "mongo:latest"
    ports:
      - "27017:27017"
